version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    tty: true
    environment:
      DB_HOST: db-container
      DB_PORT: 5432
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: template
      TZ: "Asia/Tokyo"

  db:
    image: postgres:12.3-alpine
    container_name: db-container
    ports:
      - "5432:5432"
    environment:
      TZ: "Asia/Tokyo"
      LANG: ja_JP.utf8
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: template
