name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  PROJECT_ID: -- TODO --
  RUN_REGION: -- TODO --
  SERVICE_NAME: -- TODO --
  ARTIFACT_HOST: -- TODO --
  ARTIFACT_REPO: -- TODO --
  DOCKER_BUILDKIT: 1
  INSTANCE_CONNECTION_NAME: ${{ secrets.SQL_CONNECTION_DEV }}
  DB_USER: postgres
  DB_PASS: ${{ secrets.DB_PASSWORD_DEV }}
  DB_NAME: template
  DB_PORT: 5432
  TZ: Asia/Tokyo
  LOG_LEVEL: Debug

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.SA_KEY_DEV }}

      - name: Configure Docker to use the gcloud command-line tool as a credential
        run: |-
          gcloud auth configure-docker $ARTIFACT_HOST

      - name: Build
        run: |-
          docker build --target deploy --tag "$ARTIFACT_HOST/$PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:$GITHUB_SHA" .

      - name: Push the Docker image to Google Artifact Registry
        run: |-
          docker push "$ARTIFACT_HOST/$PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:$GITHUB_SHA"

      - name: Deploy
        run: |-
          gcloud run deploy $SERVICE_NAME \
            --project $PROJECT_ID \
            --region $RUN_REGION \
            --image "$ARTIFACT_HOST/$PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated \
            --add-cloudsql-instances $INSTANCE_CONNECTION_NAME \
            --set-env-vars DB_HOST="/cloudsql/$INSTANCE_CONNECTION_NAME" \
            --set-env-vars DB_USER="$DB_USER" \
            --set-env-vars DB_PASSWORD="$DB_PASS" \
            --set-env-vars DB_NAME="$DB_NAME" \
            --set-env-vars DB_PORT=$DB_PORT \
            --set-env-vars TZ="$TZ" \
            --set-env-vars LOG_LEVEL="$LOG_LEVEL"
