name: Reviewdog

on:
  pull_request:

jobs:
  golangci-lint:
    name: Go CI Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Go CI Lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          filter_mode: nofilter
          reporter: github-pr-review
